### ISSUE TITLE
[ziwooda]watchapi

### ISSUE THREAD

**Issue by yugyeongh** [JUJY-OIDC/etcd-autobackup#5]
watch api vs events api → 실시간 데이터 변경 감지에는 watch api가 적절
- watch api : 실시간 변경 사항 감지
- events api : 이벤트 조회 및 클러스터 데이터 분석

`nginx-deployment.yaml`로 test 수행

**Comment by ziwooda** [comment]
AS-IS
- 사용자 지정 네임스페이스의 파드 변경 사항(생성, 수정, 삭제 동작)을 감지하고 현상태 출력

TO-BE
- 파드 외에 변경 사항을 감지 리소스 범위 확정
- `etcd-backup-job.yaml` 파일을 트리거하는 코드 추가
- 클러스터 정보 NCP to OCI 마이그레이션
