### ISSUE TITLE
[juyoung810, na3150] pod 외부 통신 오류 

### ISSUE THREAD

**Issue by juyoung810** [JUJY-OIDC/etcd-autobackup#50]
## 문제 상황
pod 에서 외부 통신이 안되는 오류 발생 
#46 
custom 이미지를 생성했지만 여전히 오류 발생 중 

-> service 설치,,?

**Comment by na3150** [comment]
- service가 존재하지 않음으로써 발생하는 오류로 예상했으나, ncp에서 동일한 환경 구축 후 실행했을 시에는 문제 없이 job이 completed되었다.
