### ISSUE TITLE
[yugyeongh] install etcd & save snapshot at OCI

### ISSUE THREAD

**Issue by yugyeongh** [JUJY-OIDC/etcd-autobackup#6]
- [x] oke 클러스터에 etcd 설치
- [ ] 스냅샷 생성 확인

**Comment by yugyeongh** [comment]
**1. OKE 클러스터 구축**
- 문제상황 - Node Pool에 할당된 3개의 노드 중 하나가 생성되지 않는 이슈
- 해결과정 - Bastion 생성 후 IP 연결했으나 해결X

**2. OCI 인스턴스에 k8s 설치**
- 문제상황 - 방화벽 관련 명령 실행 불가
- 해결과정 - `sudo apt-get install firewalld` 명령 실행 불가 (포트 이슈도 고려해봤으나 not working)

**Comment by yugyeongh** [comment]
**TO DO**
- OKE 클러스터에 etcd 설치
- [ ] OKE 클러스터와 Bastion Host 연결
- [ ] 오류없이 node create

**Comment by ziwooda** [comment]
AS-IS : bastion host를 통한 클러스터 통신
TO-BE : local의 kubectl로 클러스터 통신 구현

**STATUS 💭**
클러스터 접속 확인
- `kubectl cluster-info`
- `kubectl get nodes`


etcd & etcdctl 설치 완료
- `etcd --version`
- `etcdctl version`

**Comment by ziwooda** [comment]
**🤯 ISSUE on TASK-2; OKE-OIDC 연결 🤯**

context의 기존 user로는 노드 리스트가 정상 조회되지만, oidc user에 대해서는 아래와 같이 에러메시지가 뜨는 이슈

```
kubectl --user=user-c5v2e5i3ivq get nodes
NAME          STATUS   ROLES   AGE   VERSION
xxx           Ready    node    xxx   v1.26.2
xxx           Ready    node    xxx   v1.26.2
xxx           Ready    node    xxx   v1.26.2
```

```
kubectl --user=oidc get nodes
>> error: You must be logged in to the server (Unauthorized)
```

Checklists

- [ ] OIDC Client ID, Client Secret
- [ ] ~/.kube/config file
